name: Artifact
on: [push, pull_request]
env:
  ARTIFACT_NAME: myartifact
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: checkout the code
      uses:  actions/checkout@v2
    - name:  upload the artifact
      uses:  actions/upload-artifact@v2
      with: 
        name: ${{ env.ARTIFACT_NAME }}
        path: .

